[package]
name = "rong"
version = "1.0.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
bevy_rapier2d = "0.30.0"
rand = "0.9.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
